copy-paste from gitlab
ome/cookiecutter-omero-webapp pull request #1
Opened 2024-02-01 07:53 UTC by glyg

Code was previously here

https://gitlab.in2p3.fr/fbi-data/small-and-various-pieces-of-coding/omero-webapp-cookiecutter

2024-02-01 13:04 UTC, will-moore commented
Just tested this with

```
$ cookiecutter https://github.com/glyg/cookiecutter-omero-webapp.git --checkout legacy
```
and it worked fine.

```
$ cookiecutter https://github.com/glyg/cookiecutter-omero-webapp.git --checkout legacy
  [1/7] full_name (Guillaume Gay): Joe Blogs
  [2/7] email (guillaum@damcb.com): j.blogs@example.com
  [3/7] webapp_name (simple_webapp): test_app
  [4/7] webapp_title (Simple Webapp): Test App
  [5/7] description (OMERO example minimal web app): just testing
  [6/7] repo_name (omero-simple-webapp): omero-test-webapp
  [7/7] version (0.1.0): 
```

I would like to acknowledge your contribution @glyg, but maybe your name and e-mail shouldn't be the default values. In fact I'm not sure there should be default values for these since we always want users to enter something. Does it work without defaults?

I think we can tweak the README of this app (and the generated app) in follow-up PRs, but it would be good to fix the cookiecutter instruction in this PR:

```
cookiecutter https://gitlab.in2p3.fr/fbi-data/small-and-various-pieces-of-coding/omero-webapp-cookiecutter
```
should be
```
cookiecutter https://github.com/ome/cookiecutter-omero-webapp.git
```

Thanks!

2024-02-01 13:08 UTC, glyg commented
I don't think there's reason for the default email, will look into it. No worries about recognition :)

2024-02-01 13:09 UTC, glyg commented
I'll fix the url later today

2024-02-02 08:31 UTC, glyg commented
I think the json is written as an update to defaults, it shouldn't have been versioned

2024-02-02 09:23 UTC, will-moore approved these changes
Great, thanks

2024-02-02 15:25 UTC, pwalczysko commented
```
(cookicutter) pwalczysko@Petrs-MBP cookiecutter-omero-webapp % cookiecutter https://github.com/glyg/cookiecutter-omero-webapp.git --checkout legacy
You've downloaded /Users/pwalczysko/.cookiecutters/cookiecutter-omero-webapp 
before. Is it okay to delete and re-download it? [y/n] (y): y
A valid repository for "https://github.com/glyg/cookiecutter-omero-webapp.git" could not be found in the following locations:
/Users/pwalczysko/.cookiecutters/cookiecutter-omero-webapp
```

Not sure ^^^ what is missing. Tried to follow the simple README:
- cloned this repo, ``cd`` into it
- checked out this branch
- Created a new conda env cookcutter ``conda create -n cookicutter python=3.10``
- activated the env
- ``pip install cookiecutter``
- ``cookiecutter https://github.com/glyg/cookiecutter-omero-webapp.git --checkout legacy`` -> ends with error above

2024-02-02 16:26 UTC, will-moore commented
That's weird - don't know what's going on there. I get the same thing. I even tried deleting the cached repo, but it didn't help. Also tried to use the earlier commit that worked for me above, but no joy.

```
$ cookiecutter https://github.com/glyg/cookiecutter-omero-webapp.git --checkout f1d4703
You've downloaded /Users/wmoore/.cookiecutters/cookiecutter-omero-webapp before. Is it okay to delete and re-download it? [y/n] (y): y
A valid repository for "https://github.com/glyg/cookiecutter-omero-webapp.git" could not be found in the following locations:
/Users/wmoore/.cookiecutters/cookiecutter-omero-webapp

$ rm -rf /Users/wmoore/.cookiecutters/cookiecutter-omero-webapp

$ cookiecutter https://github.com/glyg/cookiecutter-omero-webapp.git --checkout legacy
A valid repository for "https://github.com/glyg/cookiecutter-omero-webapp.git" could not be found in the following locations:
/Users/wmoore/.cookiecutters/cookiecutter-omero-webapp
```

2024-02-02 17:12 UTC, will-moore commented
@glyg - I think you need to add back the `cookiecutter.json` as it look like that's essential.
I added it to my local `/Users/wmoore/.cookiecutters/cookiecutter-omero-webapp` cache, and I was then able to use that...

```
$ cookiecutter https://github.com/glyg/cookiecutter-omero-webapp.git
You've downloaded /Users/wmoore/.cookiecutters/cookiecutter-omero-webapp before. Is it okay to delete and re-download it? [y/n] (y): n
Do you want to re-use the existing version? [y/n] (y): y
  [1/7] full_name (Guillaume Gay): Will Moore
...
```
We can update defaults in a follow-up PR. Thanks.

2024-02-05 09:52 UTC, will-moore requested changes
Thanks @glyg - that's working again.
I found a couple of issues I missed before when actually installing the app

2024-02-05 09:52 UTC, will-moore commented on {{cookiecutter.repo_name}}/{{cookiecutter.webapp_name}}/views.py
> +from django.core.urlresolvers import reverse
reverse isn't used and this import actually fails on Django 4.2 so this line can be removed

2024-02-05 09:52 UTC, will-moore commented on {{cookiecutter.repo_name}}/{{cookiecutter.webapp_name}}/urls.py
> +from django.conf.urls import url
This import fails now on Django 4.2. It needs to be `from django.urls import re_path` and then replace `url()` with `re_path()` below.

2024-02-07 08:56 UTC, will-moore commented
Testing...

```
$ cookiecutter https://github.com/glyg/cookiecutter-omero-webapp.git --checkout legacy
You've downloaded /Users/wmoore/.cookiecutters/cookiecutter-omero-webapp before. Is it okay to delete and re-download it? [y/n] (y): y
  [1/7] full_name (Example): Wills_App       
  [2/7] email (login@example.com): 
  [3/7] webapp_name (simple_webapp): wills_app
  [4/7] webapp_title (Simple Webapp): Wills App
  [5/7] description (OMERO example minimal web app): test app
  [6/7] repo_name (omero-simple-webapp): omero-wills-app
  [7/7] version (0.1.0): 

$ omero config append omero.web.apps '"wills_app"'
$ ls
omero-wills-app
$ cd omero-wills-app/
$ pip install -e .
Obtaining file:///Users/wmoore/Desktop/COOKIECUTTER/omero-wills-app
  Preparing metadata (setup.py) ... done
Installing collected packages: omero-wills-app
  Running setup.py develop for omero-wills-app
Successfully installed omero-wills-app-0.1.0
```

Restarted omero-web server and went to http://localhost:4080/wills_app/

![Screenshot 2024-02-07 at 08 55 16](https://github.com/ome/cookiecutter-omero-webapp/assets/900055/65c8a390-6282-4454-bca2-113b4c254352)

2024-02-07 08:56 UTC, will-moore approved these changes
Looks good, thanks 👍

2024-02-08 16:46 UTC, joshmoore reviewed
Few minor edits in the README, but we can also get this in and then iterate on that.

Thanks, @glyg!

2024-02-08 16:46 UTC, joshmoore commented on README.md
> +This repository offers a  for OMERO web app by creating a project skeleton. It is based on the Django example from here: https://github.com/ome/omero-web-apps-examples
```suggestion
This repository offers a template for an OMERO web app by creating a project skeleton.
It is based on the Django example from https://github.com/ome/omero-web-apps-examples
```

2024-02-08 16:46 UTC, joshmoore commented on {{cookiecutter.repo_name}}/setup.py
> +    keywords=["omero", "example"],
```suggestion
    keywords=["omero"],
```

2024-02-08 16:46 UTC, joshmoore commented on {{cookiecutter.repo_name}}/README.md
> +This repository contains an
```suggestion
This repository contains a
```

2024-02-08 16:46 UTC, joshmoore commented on {{cookiecutter.repo_name}}/README.md
> +of a minimal omero webapp, derived from openmicroscopy [webapp examples](https://github.com/ome/omero-web-apps-examples).
```suggestion
of a minimal OMERO webapp, derived from openmicroscopy [webapp examples](https://github.com/ome/omero-web-apps-examples).
```

2024-02-08 16:46 UTC, joshmoore commented on {{cookiecutter.repo_name}}/README.md
> +This template repository contains a minimal example of OMERO.web apps minimal example (no JavaScript dependencies or build steps).
```suggestion
This repository contains a minimal OMERO.web app (no JavaScript dependencies or build steps).
```

2024-02-09 09:14 UTC, will-moore commented
Thanks all!

2024-02-09 09:14 UTC, merged