Update READMEs and remove legacy info
ome/cookiecutter-omero-webapp pull request #2
Opened 2024-02-09 10:41 UTC by will-moore

This adds a few tips and a bit more info to the README of this app, to give users a better idea of what to expect and give a few tips.

Also removes some legacy info from the new app's README (on JS frameworks etc).

Needs some discussion about duplication of info from https://omero.readthedocs.io/en/stable/developers/Web/CreateApp.html (how to run with Docker in particular).

Do we want this info on the README of *this* app (possibly), or the README of the app that gets created (probably not as this will get outdated once apps are created), or *only* on the readthedocs?

2024-02-16 16:48 UTC, pwalczysko commented on {{cookiecutter.repo_name}}/README.md
> +Add the app to the `omero.web.apps`{.interpreted-text role="property"} setting:
should this be interpreted ?

2024-02-16 16:50 UTC, pwalczysko requested changes
one question https://github.com/ome/cookiecutter-omero-webapp/pull/2#discussion_r1492735979 otherwise lgtm

2024-02-16 17:09 UTC, will-moore commented on {{cookiecutter.repo_name}}/README.md
> +Add the app to the `omero.web.apps`{.interpreted-text role="property"} setting:
Fixed in d8e2491

2024-02-19 13:34 UTC, will-moore commented
@pwalczysko - fixed that issue. OK to merge?
Any objections @jburel?

2024-02-19 13:36 UTC, pwalczysko approved these changes

2024-02-21 09:26 UTC, merged